### ISSUE TITLE
Enhancement: Add Interfaces

### ISSUE THREAD

**Issue by dafriend** [Neoflow/Session#1]
A good rule when designing for using a container and dependency injection is to type-hint against interfaces. I'd like to seem them implemented in Neoflow/Session.

**Comment by Alpine418** [comment]
Already planned, but after my holidays. 😉 Next prerelease will have them.

**Comment by dafriend** [comment]
Excellent! 
While I noticed the initial commit was very recent I did not notice that you're still in alpha. How fun to find your efforts at this early stage. I like your answer to flash data.

Have you considered implementing the [Iterator Interface](https://www.php.net/manual/en/class.iterator.php) to accomplish the same thing that `each(callable $callback)` seems to be addressing?

**Comment by Alpine418** [comment]
First drafts of the library had ArrayAccess and Iterator Interface implemented. But I don't like the array behaviour of objects and directly "unused" interface methods like offsetGet, etc. 

But please let me think about your idea, to get Iterable Interface implemented and remove the each method therefor, until my holidays ended. I will answer you again mid next week.

Best regards, rjgamer

**Comment by Alpine418** [comment]
First beta released with Interfaces published: https://github.com/Neoflow/Session/releases/tag/1.0.0-beta

Thanks for your interest and support!

Please note, that I don't plan to implement array-oriented interfaces like ArrayAccess or Iterator. But you can use `$session->toArray()` and get any array-oriented possibilities. You can also use `$session->merge()` to add the array into the session again.

**Comment by dafriend** [comment]
The interfaces look good.

Implementing `Iterator` is very easy. You just have to map from the `Iterator` methods to the matching `ArrayIterator` methods of the appropriate array.

Something to consider?

```
    public function rewind()
    {
        return reset($_SESSION[$this->key]);
    }

    public function current()
    {
        return current($_SESSION[$this->key]);
    }

    public function key()
    {
        return key($_SESSION[$this->key]);
    }

    public function next()
    {
        return next($_SESSION[$this->key]);
    }

    public function valid(): bool
    {
        return key($_SESSION[$this->key]) !== null;
    }

**Comment by Alpine418** [comment]
In my opinion, helper classes should not have an array-oriented behavior. But I also want consistency, which is with Iterator interface not possible to implement for both helper classes. Because the flash helper class handles 2 types of data: Old and new flash messages. 

Please don't be mad at me if I currently won't implement it.

**Comment by Alpine418** [comment]
I will take a nap and think about it again. Maybe I will support array-oriented behavior for the helper classes, but with limitations.

Examples of my idea:
```php
$session['key'] = 'value'; 
// alternative to:  $session->set('key', 'value')

$session->flashNew['key'] = 'value'; 
// alternative to: $session->flash()->setNew('key', 'value')

foreach ($session as $key => $value) { 
     // your custom code
}
// alternative to: $session->each(...)

foreach ($session->flashNew as $key => $value) { 
     // your custom code
}
// alternative to: $session->flash()->eachNew(...)
```

**Comment by Alpine418** [comment]
I made my decision. 

I prefer a simple and easy to understand library interface with methods only. Mixing array behaviors with methods would collide two worlds (OOP / array), that don't fit together very well. Also the the additional methods for supporting the array behavior would bloat up the code.
